<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20704" started-at="2020-02-12T01:49:30Z" finished-at="2020-02-12T01:49:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20704" started-at="2020-02-12T01:49:30Z" finished-at="2020-02-12T01:49:51Z">
      <class name="com.project.suitea.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.project.suitea.LoginTest@6a41eaa2]" name="init" is-config="true" duration-ms="1352" started-at="2020-02-12T01:49:30Z" finished-at="2020-02-12T01:49:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="login(java.util.Hashtable)[pri:0, instance:com.project.suitea.LoginTest@6a41eaa2]" name="login" duration-ms="19266" started-at="2020-02-12T01:49:32Z" data-provider="getData" finished-at="2020-02-12T01:49:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{ExpectedResult=LoginSuccess, CustomerPassword=zoho2015, CustomerName=ravilella.2015@gmail.com, Runmode=Y, Browser=chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="login(java.util.Hashtable)[pri:0, instance:com.project.suitea.LoginTest@6a41eaa2]" name="login" duration-ms="3" started-at="2020-02-12T01:49:51Z" data-provider="getData" finished-at="2020-02-12T01:49:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{ExpectedResult=LoginSuccess, CustomerPassword=P2, CustomerName=U2, Runmode=N, Browser=firefox}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[RunMode is set to No]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: RunMode is set to No
at com.project.suitea.LoginTest.login(LoginTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="login(java.util.Hashtable)[pri:0, instance:com.project.suitea.LoginTest@6a41eaa2]" name="login" duration-ms="2" started-at="2020-02-12T01:49:51Z" data-provider="getData" finished-at="2020-02-12T01:49:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{ExpectedResult=LoginFailure, CustomerPassword=P3, CustomerName=U3, Runmode=N, Browser=ie}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[RunMode is set to No]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: RunMode is set to No
at com.project.suitea.LoginTest.login(LoginTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.project.suitea.LoginTest@6a41eaa2]" name="afterTest" is-config="true" duration-ms="1" started-at="2020-02-12T01:49:51Z" finished-at="2020-02-12T01:49:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.project.suitea.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
